from typing import Dict, List

fish_data: Dict[str, List[str]] = {
    "Empty Can":            ["Greenhorn Shore", "Breadcrumb Bay", "Melonbread Cove", "Pudding", "Rust Gear Gulf", "Chemical Waste Zone"],
    "Sega Bass":            ["Greenhorn Shore", "Breadcrumb Bay"],
    "Cornfish":             ["Greenhorn Shore"],
    "Orbfish":              ["Greenhorn Shore"],
    "Badge Betta":          ["Greenhorn Shore"],
    "Taiyaki":              ["Breadcrumb Bay", "Melonbread Cove"],
    "Fugu Fish":            ["Breadcrumb Bay"],
    "Rotten Mackerel":      ["Breadcrumb Bay"],
    "Luvdisc":              ["Melonbread Cove", "Chemical Waste Zone"],
    "Helmet Jelly":         ["Melonbread Cove"],
    "Whip Eel":             ["Melonbread Cove"],
    "Tuna Sashimi":         ["Melonbread Cove", "Big Bone Bay"],
    "Angler":               ["Pudding", "Rust Gear Gulf", "Chemical Waste Zone", "Big Bone Bay"],
    "Rubber Duckie":        ["Pudding"],
    "Blobfish Buddy":       ["Pudding"],
    "Haliberd":             ["Pudding"],
    "Goldfish Cracker":     ["Pudding"],
    "Mechanical Carp":      ["Rust Gear Gulf"],
    "Cum Buddy":            ["Rust Gear Gulf"],
    "Son of Lokey":         ["Rust Gear Gulf", "Stardrop Tree"],
    "Pagliacci":            ["Chemical Waste Zone"],
    "Blinky":               ["Chemical Waste Zone"],
    "Undyne JR":            ["Big Bone Bay"],
    "Whale Shark Onesie":   ["Big Bone Bay"],
    "Angeler":              ["Big Bone Bay", "Stardrop Tree"],
    "Sansfish":             ["Big Bone Bay"],
    "Angelfish":            ["Stardrop Tree"],
    "Leviathan":            ["Stardrop Tree"],
    "Pisces":               ["Stardrop Tree"],
    "Tsuchinoko":           ["Stardrop Tree"],
    "Morsel":               ["Heaven"],
    "Expio":                ["Heaven"],
    "Soupie":               ["Heaven"],
    "Rezzie":               ["Heaven"],
    "Mem-F":                ["Flowey Room"],
    "Mem-Y":                ["Flowey Room"],
    "Mem-G":                ["Flowey Room"],
    "Wrangler":             ["Flowey Room"]
}

fish_quests: List[str] = ["Sega Bass", "Fugu Fish", "Rotten Mackerel", "Luvdisc", "Tuna Sashimi", "Goldfish Cracker", "Angler", "Pagliacci", "Whale Shark Onesie", "Leviathan", "Tsuchinoko"]